services:
  postgres:
    image: postgres:16-alpine
    container_name: merchant_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: merchant_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build: ./backend
    container_name: merchant_backend
    expose:
      - "8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/merchant_db
      CORS_ORIGINS: '["http://localhost","http://merchantpay.work.gd"]'
      DEBUG: "false"
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: /api/v1
    container_name: merchant_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pgdata:
